NAME[0]="Ranjan"
NAME[1]="Kumar"
NAME[2]="Thakur"
NAME[3]="Flutter"
NAME[4]="Developer"
echo "First Index: ${NAME[0]}"
echo "Second Index: ${NAME[1]}"
echo "First Index: ${NAME[*]}"
echo "Second Index: ${NAME[@]}"